### ISSUE TITLE
Tela de criação de usuário

### ISSUE THREAD

**Issue by NKKFu** [Senom-Dot/adm-dashboard#1]
A tela de criação de usuário deverá ser acessada pelo caminho /new-user e..

Deve conter:
- Nome de usuário a ser criado
- Senha de usuário a ser criada
- Visualizar/esconder a senha de usuário (por padrão, é escondida)
- Aviso de sucesso ou erro (em caso de erro, dizer qual o erro)

**Não é para fazer a estilização agora, pois utilizaremos styled-components no futuro** 
Por enquanto é necessário implementar as funcionalidades.

**Comment by NKKFu** [comment]
Utilizar esta biblioteca para os erros, já que facilita na criação deles:

https://www.npmjs.com/package/react-toastify

**Comment by Al3xsandro** [comment]
- PR Aberto: https://github.com/Senom-Dot/adm-dashboard/pull/3
